# What is Numpy?
Numpy stands for Numerical python which is a python package for the computation and processing of the multi-dimensional and single-dimensional array elements.

In [29]:
# import numpy library
import numpy as np

In [30]:
# 1d array
arr1=np.array([1.4,3.4,4.8])
print(arr1)
print("No.of dimensions are",arr1.ndim)
print("Array Size:",arr1.size)
print("Elements size:",arr1.itemsize)
print("--------------------------------\n")

[1.4 3.4 4.8]
No.of dimensions are 1
Array Size: 3
Elements size: 8
--------------------------------



In [31]:
'''Enter array values through user.
l=[]
n1=int(input("Enter Array Size:"))
print("Enter",n1,"Numbers:")
for i in range(n1):
    n2=int(input())
    l.append(n2)

arr=np.array(l)
print("Array is:",arr)'''

'Enter array values through user.\nl=[]\nn1=int(input("Enter Array Size:"))\nprint("Enter",n1,"Numbers:")\nfor i in range(n1):\n    n2=int(input())\n    l.append(n2)\n\narr=np.array(l)\nprint("Array is:",arr)'

# 2d array 
           It also called matrix.

In [32]:
# 1st way
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)
print("No.of dimensions are",arr2.ndim)
print("Array Size:",arr2.size)
print("Elements size:",arr1.itemsize)
print("--------------------------------\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
No.of dimensions are 2
Array Size: 12
Elements size: 8
--------------------------------



In [33]:
# 2nd way -using arange(start,stop,step)
arr2=np.arange(16).reshape(4,4)                           #2d array-  reshape(row,column)
print(arr2) 
print("No.of dimensions are",arr2.ndim)
print("Array Size:",arr2.size)
print("Elements size:",arr2.itemsize)
print("Array size(row*column):",arr2.shape)
print("-----------------------------------")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
No.of dimensions are 2
Array Size: 16
Elements size: 4
Array size(row*column): (4, 4)
-----------------------------------


In [34]:
# append elements inside an array using append()
arr=np.array([[1,2,3],[4,5,6]])
print("First Array:\n",arr)

print("\nAppend Elements to array:")
print(np.append(arr,[7,8,9]))

First Array:
 [[1 2 3]
 [4 5 6]]

Append Elements to array:
[1 2 3 4 5 6 7 8 9]


# 3d array

In [35]:
# 1st way
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])  
print(arr3)
print("No.of dimensions are",arr3.ndim)
print("Array Size:",arr3.size)
print("Array size(no. of matrix, row , column):",arr3.shape)
print("-------------------------------------")


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
No.of dimensions are 3
Array Size: 12
Array size(no. of matrix, row , column): (1, 4, 3)
-------------------------------------


In [36]:
# 2nd way -using arange(start,stop,step)
arr3=np.arange(27).reshape(3,3,3)                           #3d array-  reshape(no. of matrix, row , column)             
print(arr3)
print("No.of dimensions are",arr3.ndim)
print("Array Size:",arr3.size)
print("Array size(no. of matrix, row , column):",arr3.shape)
print("-------------------------------------")


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
No.of dimensions are 3
Array Size: 27
Array size(no. of matrix, row , column): (3, 3, 3)
-------------------------------------


# Zeros() & Ones()

In [37]:
# Intialize array with 0's[ zeros((row,column)) ] and 1's[ ones(row,column)) ]
arr= np.zeros((3,4))
print(arr)
print("No.of dimensions are",arr.ndim)
print("Array Size:",arr.size)
print("-------------------------------------")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
No.of dimensions are 2
Array Size: 12
-------------------------------------


In [38]:
arr= np.ones((3,4,3))                        # array size = no. of matrix*row*column
print(arr)
print("No.of dimensions are",arr.ndim)
print("Array Size:",arr.size)
print("-------------------------------------")

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
No.of dimensions are 3
Array Size: 36
-------------------------------------


# Arithmetic o/p on 2d-array

In [39]:
# note: both array row & column size must be same.
arr1=np.arange(12,24).reshape(3,4)
print(arr1)
print("-------------------------------------")

arr2=np.arange(24,36).reshape(3,4)
print(arr2)
print("-------------------------------------")

print("arr2/arr1:\n",arr2/arr1)
print("arr2*arr1:\n",arr2*arr1)
print("arr2+arr1:\n",arr2+arr1)
print("arr2-arr1:\n",arr2-arr1)
print("-------------------------------------")

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-------------------------------------
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
-------------------------------------
arr2/arr1:
 [[2.         1.92307692 1.85714286 1.8       ]
 [1.75       1.70588235 1.66666667 1.63157895]
 [1.6        1.57142857 1.54545455 1.52173913]]
arr2*arr1:
 [[288 325 364 405]
 [448 493 540 589]
 [640 693 748 805]]
arr2+arr1:
 [[36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]
arr2-arr1:
 [[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
-------------------------------------


# Relational o/p on 2d-array

In [40]:
#note: both array row & column size must be same. - returns boolean value.
arr1=np.arange(12).reshape(3,4)
print(arr1)
print("-------------------------------------")

arr2=np.arange(12,24).reshape(3,4)
print(arr2)
print("-------------------------------------")

print("arr2>arr1:\n",arr2>arr1)
print("arr2<arr1:\n",arr2<arr1)
print("arr2==arr1:\n",arr2==arr1)
print("-------------------------------------")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-------------------------------------
arr2>arr1:
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
arr2<arr1:
 [[False False False False]
 [False False False False]
 [False False False False]]
arr2==arr1:
 [[False False False False]
 [False False False False]
 [False False False False]]
-------------------------------------


# Max, Min, Sum, Product(prod)

In [41]:
arr=np.arange(12,24).reshape(3,4)
print(arr)
print("-------------------------------------")

print("Largest element is",np.max(arr))
print("Smallest element is",np.min(arr))
print("Sum of all array element is",np.sum(arr))
print("Product of arr1 & arr2 is",np.prod(arr))
print("-------------------------------------\n")

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-------------------------------------
Largest element is 23
Smallest element is 12
Sum of all array element is 210
Product of arr1 & arr2 is 816826368
-------------------------------------



# Mean, Median, Standard deviation, Variance

In [42]:
arr=np.arange(12,24).reshape(3,4)
print(arr)
print("-------------------------------------")

print("Mean is",np.mean(arr))
print("Median  is",np.median(arr))
print("Standard Deviation is",np.std(arr))
print("Variance is",np.var(arr))
print("-------------------------------------")

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-------------------------------------
Mean is 17.5
Median  is 17.5
Standard Deviation is 3.452052529534663
Variance is 11.916666666666666
-------------------------------------


# Dot Product

In [43]:
# Dot Product only possible when 1st matrix row value and 2nd matrix column value is SAME.  
arr1=np.arange(12).reshape(3,4)
print(arr1)
print("-------------------------------------")

arr2=np.arange(12,24).reshape(4,3)
print(arr2)
print("-------------------------------------")

print("Dot product is:\n",np.dot(arr1,arr2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
-------------------------------------
Dot product is:
 [[114 120 126]
 [378 400 422]
 [642 680 718]]


# Log and Exponent

In [44]:
arr1=np.arange(12,24).reshape(3,4)
print(arr1)
print(np.log(arr1))
print(np.exp(arr1))
print("-------------------------------------")

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[2.48490665 2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176 2.94443898]
 [2.99573227 3.04452244 3.09104245 3.13549422]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
 [8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09]]
-------------------------------------


# Round, Floor, Ceil

In [45]:
arr=np.array([[1.5,5.3,7.3],[2.4,7.4,8.2],[6.2,8.1,3.6]])
print(arr)
print("Removing Decimal Values-",np.round(arr))
print("Before Decimal value",np.floor(arr))
print("Decimal value + 1",np.ceil(arr))
print("-------------------------------------")

[[1.5 5.3 7.3]
 [2.4 7.4 8.2]
 [6.2 8.1 3.6]]
Removing Decimal Values- [[2. 5. 7.]
 [2. 7. 8.]
 [6. 8. 4.]]
Before Decimal value [[1. 5. 7.]
 [2. 7. 8.]
 [6. 8. 3.]]
Decimal value + 1 [[2. 6. 8.]
 [3. 8. 9.]
 [7. 9. 4.]]
-------------------------------------


# Indexing

In [46]:
arr1=np.arange(12).reshape(3,4)
print(arr1)
print(arr1[1,1])
print(arr1[2,3])
print("-------------------------------------")

arr2=np.arange(36).reshape(3,4,3)       # reshape(no. of matrix, row, column)
print(arr2)
print(arr2[1,2,1])
print(arr2[0,3,2])
print("-------------------------------------")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5
11
-------------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
19
11
-------------------------------------


# Slicing in numpy array

                           
syntax: 2d array:
                    ----Row-------,---Column-----
         array_name[start:end:step,start:end:step]

        3d array:
         
                   no. of matrix--,-----Row------,---Column-----
         array_name[no. of matrix,start:end:step,start:end:step]


start - index of the first element included (by default starts with 0)
stop - index of the last element excluded
step - step size between each element (by default incremented by 1)

In [47]:
# Slicing
arr=np.arange(16).reshape(4,4)
print(arr)
# aim- 2 3
print(arr[0,2:])
print(arr[1,:])
print(arr[:,1])
print(arr[1:3,1:3])
# aim- 9 10
print(arr[2:3,1:3])
print(arr[1:3,])
print(arr[:,1:3])
print(arr[1:3,1])
print(arr[1:3,:1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[2 3]
[4 5 6 7]
[ 1  5  9 13]
[[ 5  6]
 [ 9 10]]
[[ 9 10]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[5 9]
[[4]
 [8]]


# Iteration

 reshape syntax: 
                2d array:- reshape(row,column)
                3d array:- reshape(matrix no,row,column)

In [48]:
# 1D-array
arr=np.arange(12)
print(arr)
print("Printing 1d array elements through iteration:")
for i in arr:
    print(i)
print("----------------------------")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Printing 1d array elements through iteration:
0
1
2
3
4
5
6
7
8
9
10
11
----------------------------


In [49]:
# 2D-array
arr=np.arange(12).reshape(4,3)
print(arr)
print("Printing 2d array elements through iteration:")
for i in arr:
    print(i)
print("----------------------------")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Printing 2d array elements through iteration:
[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
----------------------------


In [50]:
# 3D-array
arr=np.arange(36).reshape(4,3,3)
print(arr)
print("Printing 3d array elements through iteration:")
for i in arr:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
Printing 3d array elements through iteration:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
[[27 28 29]
 [30 31 32]
 [33 34 35]]


In [51]:
# 3D-array
arr=np.arange(36).reshape(4,3,3)
print(arr)

# Access every element of Multi-dimensional array using nditer(array_name) function. 
for i in np.nditer(arr):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


#  Transpose and Ravel

Transpose- convert row value into column value.
Ravel-  convert multi-dimensional array into single-dimensional array.

In [52]:
import numpy as np

arr1=np.arange(12).reshape(3,4)
print(arr1)

# Transpose- convert row value into column value.
print("2d Array after tanspose:")
print(np.transpose(arr1))
print(arr1.T)                                # Both methods are same.

# Ravel- convert multi-dimensional array into single-dimensional array.
print("2d Array after ravel:")
print(arr1.ravel())

# 3d-array
arr2=np.arange(36).reshape(4,3,3)

print("3d Array after ravel:")
print(arr2.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2d Array after tanspose:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
2d Array after ravel:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
3d Array after ravel:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


# Stacking 
           It used to joint any 2 numpy arrays.
           There are two ways to adding an numpy array-
           1) Horizantally
           2) Vertically

Note- Both array row & column value will be same. if it is not then it will give an error.

In [53]:
arr1=np.arange(12).reshape(3,4)
print(arr1)
arr2=np.arange(12,24).reshape(3,4)
print(arr2)

#np.hstack((arr1,arr2))- passing tuple as an argument
print("Horizantally adding two arrays:\n",np.hstack((arr1,arr2)))   
print("___________________________________________________")
print("Vertically adding two arrays:\n",np.vstack((arr1,arr2)))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Horizantally adding two arrays:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
___________________________________________________
Vertically adding two arrays:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Spliting 
           It split any numpy array either horizantally or vertically.
           syntax- hsplit(array_name,how many parts u want to split)
                   vsplit(array_name,how many parts u want to split)

In [54]:
arr=np.arange(12).reshape(3,4)
print(arr)

print("Spliting numpy array horizantally:")
print(np.hsplit(arr,2))

print("---------------------------------")
print("Spliting numpy array vertically:")
print(np.vsplit(arr,3))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Spliting numpy array horizantally:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
---------------------------------
Spliting numpy array vertically:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
